### ISSUE TITLE
Import and Populate Sample data from CSV to MongoDB

### ISSUE THREAD

**Issue by nabinthomas** [nabinthomas/cmpe272assignment#7]
Assignment 2: Part 1. populate the sample data (eg. by importing it from some CSV files).

And write unit test cases for these. 

Need import for books, customers and orders.  ( Use multiple csv files to do unit testing)

**Comment by binukjose** [comment]
Part 1. populate the sample data ,Following are the input files 
books.csv,   books.schema.json
customers.csvc,   customers.schema.json
orders.csv,   orders.schema.json
